services:
  opnsense_vouchers:
    container_name: opnsense_vouchers
    build:
      context: .
      dockerfile: Dockerfile
    image: knom/opnsense_vouchers
    ports:
       - "3030:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - BASEPATH=/wifi/
    volumes:
      - ./data:/app/data
    restart: always
